-- @path: sys/policy/wallust/wallust-hyprland.lua
-- @author: redskaber
-- @date: 2026-08-20
-- @description: Wallust color variables (auto-generated by wallust)
-- @version: v55.0 up

return {
	background = "#1E1F1F",
	foreground = "#EBEBEB",
	color0 = "#444545",
	color1 = "#151718",
	color2 = "#151718",
	color3 = "#272C2E",
	color4 = "#282E2F",
	color5 = "#57676A",
	color6 = "#949594",
	color7 = "#DADADA",
	color8 = "#989999",
	color9 = "#1C1F20",
	color10 = "#1C1F20",
	color11 = "#333B3D",
	color12 = "#353D3F",
	color13 = "#74898E",
	color14 = "#C5C6C6",
	color15 = "#DADADA",
}
