# /* wallust template - colors-hyprland */ 

$background = rgb(191B1C)
$foreground = rgb(E5E7EE)
$color0 = rgb(404143)
$color1 = rgb(161C23)
$color2 = rgb(171F28)
$color3 = rgb(434853)
$color4 = rgb(54555F)
$color5 = rgb(696E7B)
$color6 = rgb(878C9B)
$color7 = rgb(D1D4DE)
$color8 = rgb(92949B)
$color9 = rgb(1E252F)
$color10 = rgb(1F2A35)
$color11 = rgb(5A616E)
$color12 = rgb(70717F)
$color13 = rgb(8C92A4)
$color14 = rgb(B4BACE)
$color15 = rgb(D1D4DE)
