-- @path: sys/policy/wallust/wallust-hyprland.lua
-- @author: redskaber
-- @date: 2026-08-20
-- @description: Wallust color variables (auto-generated by wallust)
-- @version: v55.0 up

return {
	background = "#1D1C1D",
	foreground = "#EFEAE8",
	color0 = "#434344",
	color1 = "#776C69",
	color2 = "#776C69",
	color3 = "#9C928C",
	color4 = "#9D938D",
	color5 = "#9E938D",
	color6 = "#9E938D",
	color7 = "#E0D9D5",
	color8 = "#9D9895",
	color9 = "#9F908C",
	color10 = "#9F908C",
	color11 = "#D0C2BA",
	color12 = "#D2C4BC",
	color13 = "#D2C4BC",
	color14 = "#D2C4BC",
	color15 = "#E0D9D5",
}
