# /* wallust template - colors-hyprland */ 

$background = rgb(1E1F1F)
$foreground = rgb(EBEBEB)
$color0 = rgb(444545)
$color1 = rgb(151718)
$color2 = rgb(151718)
$color3 = rgb(272C2E)
$color4 = rgb(282E2F)
$color5 = rgb(57676A)
$color6 = rgb(949594)
$color7 = rgb(DADADA)
$color8 = rgb(989999)
$color9 = rgb(1C1F20)
$color10 = rgb(1C1F20)
$color11 = rgb(333B3D)
$color12 = rgb(353D3F)
$color13 = rgb(74898E)
$color14 = rgb(C5C6C6)
$color15 = rgb(DADADA)
