-- @path: sys/policy/wallust/wallust-hyprland.lua
-- @author: redskaber
-- @date: 2026-08-20
-- @description: Wallust color variables (auto-generated by wallust)
-- Note: Colors use #hex format (wiki: "#fafc21" or "rgb(...)" or "rgba(...)")
-- wallust should generate this file with #hex values.

return {
	background = "#191B1C",
	foreground = "#E5E7EE",
	color0 = "#404143",
	color1 = "#161C23",
	color2 = "#171F28",
	color3 = "#434853",
	color4 = "#54555F",
	color5 = "#696E7B",
	color6 = "#878C9B",
	color7 = "#D1D4DE",
	color8 = "#92949B",
	color9 = "#1E252F",
	color10 = "#1F2A35",
	color11 = "#5A616E",
	color12 = "#70717F",
	color13 = "#8C92A4",
	color14 = "#B4BACE",
	color15 = "#D1D4DE",
}
