-- @path: sys/const.lua
-- @author: redskaber
-- @date: 2026-08-20
-- @version: 4.0
-- @description: Layer 2: system default constants (vendor, read-only)
--
-- ARCHITECTURE (Task 90): SSOT for ALL paths + DI variables.
--   This module is the SINGLE SOURCE OF TRUTH for:
--     - Application commands (terminal, editor, ...)
--     - Modifier key
--     - Internal directory paths (scripts, hardware, policy, ...)
--     - External tool config paths (swaync, rofi, waybar, wallust, kitty, qt)
--     - Helper tags
--     - Search engine
--     - Wallpaper directory
--
--   These values flow to two consumers:
--     1. Lua config (via require("const") → merged by bootstrap/default.lua)
--     2. Shell scripts (via deps.export_to_shell() → .deps_cache.sh)
--
--   User overrides in user/const.lua replace specific keys (incremental override).

local paths = require("bootstrap.const")

local M = {}

-- bootstrap::paths base use
M.home_dir = paths.home_dir
M.cache_dir = paths.cache_dir
M.wallpaper_dir = paths.wallpaper_dir

M.xdg_config = paths.xdg_config
M.config_hypr = paths.config_hypr

M.bootstrap = paths.bootstrap
M.sys = paths.sys
M.user = paths.user

M.wallust_effects = paths.wallust_effects
M.lock_background = paths.lock_background

M.notify_icon = paths.notify_icon
M.search_engine = paths.search_engine

-- ── Main modifier key ──────────────────────────────────────────────────────
M.modifier = "SUPER"

-- ── Application commands (resolved via deps.lua at use site) ──────────────
M.apps = {
	terminal = "kitty",
	file_manager = "nemo",
	editor = os.getenv("EDITOR") or "nano",
}

-- ── Internal directory paths (derived from config_hypr, never hard-coded) ───
M.dirs = {
	scripts = paths.sys .. "/scripts",
	hardware = paths.sys .. "/hardware",
	policy = paths.sys .. "/policy",
	wallust = paths.sys .. "/policy/wallust",
	animations = paths.sys .. "/policy/animations",
	-- User-side equivalents (for user/ overrides)
	user_scripts = paths.user .. "/scripts",
	user_hardware = paths.user .. "/hardware",
	user_policy = paths.user .. "/policy",
	user_wallust = paths.user .. "/policy/wallust",
	user_animations = paths.user .. "/policy/animations",
}

-- ── External tool config directories (SSOT for shell scripts too) ─────────
-- These are exported to .deps_cache.sh by M.export_to_shell().
-- Users override via user/const.lua M.external or env vars.
--
-- NAMING: ALL keys end in "_DIR" (or "_ICONS"/"_IMAGES" for sub-paths).
--   export_to_shell converts to UPPER_SNAKE_CASE: swaync_dir → SWAYNC_DIR.
M.external = {
	-- execute
	rofi = "rofi",
	gdk_backend = "wayland",

	-- dirs
	swaync_dir = paths.xdg_config .. "/swaync",
	swaync_icons = nil, -- derived below
	swaync_images = nil, -- derived below
	rofi_dir = paths.xdg_config .. "/rofi",
	waybar_dir = paths.xdg_config .. "/waybar",
	wallust_dir = paths.xdg_config .. "/wallust",
	kitty_dir = paths.xdg_config .. "/kitty",
	qt_dir = paths.xdg_config .. "/qt",
}

-- Derive sub-paths (from swaync_dir)
M.external.swaync_icons = M.external.swaync_dir .. "/icons"
M.external.swaync_images = M.external.swaync_dir .. "/images"

-- ── Helper tags (window tag names for help/config UI) ──────────────────────
M.helpers = {
	cheat = "Help_Cheat",
	settings = "Help_Settings",
}

-- ════════════════════════════════════════════════════════════════════════════
-- Shell Export: generate .deps_cache.sh from this SSOT
-- ════════════════════════════════════════════════════════════════════════════
-- Called by bootstrap/default.lua after merging user overrides.
-- Exports ALL constants (apps + dirs + external) as shell variables.
-- Shell scripts source .deps_cache.sh to get DI variables.

function M.export_to_shell()
	local const = require("const") -- get merged const (with user overrides)
	local f = io.open(const.deps_cache_file, "w")
	if not f then
		return false
	end

	f:write("#!/bin/sh\n")
	f:write("# AUTO-GENERATED by sys/const.lua M.export_to_shell()\n")
	f:write(string.format("# Source this in .sh: source ${HYPR_DEPS_CACHE:-%q}\n", const.deps_cache_file))
	f:write("# This is the SINGLE SOURCE OF TRUTH for all paths + DI variables.\n\n")

	-- Config paths
	f:write(string.format("export HYPR_CONFIG_DIR=%q\n", const.config_hypr))
	f:write(string.format("export HYPR_SCRIPTS_DIR=%q\n", const.dirs.scripts))
	f:write(string.format("export HYPR_HARDWARE_DIR=%q\n", const.dirs.hardware))
	f:write(string.format("export HYPR_POLICY_DIR=%q\n", const.dirs.policy))
	f:write(string.format("export HYPR_SYS_DIR=%q\n", const.sys))
	f:write(string.format("export HYPR_USER_DIR=%q\n", const.user))
	f:write(string.format("export HYPR_SEARCH_ENGINE=%q\n", const.search_engine))
	f:write(string.format("export HYPR_WALLUST_DIR=%q\n", const.wallust_effects))
	f:write(string.format("export HYPR_LOCK_BG=%q\n", const.lock_background))
	f:write(string.format("export HYPR_NOTIFY_ICON=%q\n", const.notify_icon))
	f:write(string.format("export HYPR_WALLPAPER_DIR=%q\n", const.wallpaper_dir))
	f:write(string.format("export HYPR_CACHE_DIR=%q\n", const.cache_dir))
	f:write("\n")

	-- External tool config paths
	for name, path in pairs(const.external) do
		local var = name:upper()
		f:write(string.format("export %s=%q\n", var, path))
	end
	f:write("\n")

	-- Application commands (from deps.lua specs too)
	local deps = require("lib.deps")
	for name in pairs(deps.specs) do
		local dep = deps.get(name)
		if dep and dep.cmd and dep.cmd ~= "" then
			local var = name:upper():gsub("-", "_")
			f:write(string.format("export %s=%q\n", var, dep.cmd))
		end
	end

	f:close()
	return true
end

return M
