$M              = SUPER
$M_terminal     = kitty
$M_file_manager = nemo
$M_editor       = ${EDITOR:-nano}

$S              = $sys/scripts
$H              = $sys/hardware
$P              = $sys/policy
$P_w            = $P/wallust
$P_a            = $P/animations

# Helper window tags
$H_Cheat        = Help_Cheat
$H_Settings     = Help_Settings

# Wallpapers
$W              = $HOME/Pictures/wallpapers
$W_l            = ""

$U              = $user
$U_s            = $user/scripts
$U_h            = $user/hardware
$U_p            = $user/policy
$U_pw           = $U_p/wallust
$U_pa           = $U_p/animations

$I_notify       = $Hypr/icon.png
$Search_Engine  = "https://www.google.com/search?q={}"


