# sys/misc.conf — Miscellaneous Hyprland options
# $M_terminal is available here (defined in bootstrap/const.conf, Stage 0).

misc {
    disable_hyprland_logo        = true
    disable_splash_rendering     = true
    vrr                          = 2
    mouse_move_enables_dpms      = true
    enable_swallow               = off
    swallow_regex                = ^($M_terminal)$
    focus_on_activate            = false
    initial_workspace_tracking   = 0
    middle_click_paste           = false
    enable_anr_dialog            = true
    anr_missed_pings             = 15
    allow_session_lock_restore   = true
}

debug {
    vfr                          = true # `misc` moved to `debug` from v0.55
}


