# /* wallust template - colors-hyprland */

$background = rgb(191C1D)
$foreground = rgb(F7F2D0)
$color0 = rgb(3F4343)
$color1 = rgb(0E1C1B)
$color2 = rgb(353A25)
$color3 = rgb(2E3D25)
$color4 = rgb(546331)
$color5 = rgb(5E6E34)
$color6 = rgb(AFA45A)
$color7 = rgb(ECE5B3)
$color8 = rgb(A5A07D)
$color9 = rgb(132524)
$color10 = rgb(474D31)
$color11 = rgb(3E5132)
$color12 = rgb(708441)
$color13 = rgb(7E9246)
$color14 = rgb(E9DB78)
$color15 = rgb(ECE5B3)
