# /* wallust template - colors-hyprland */ 
$background = rgb(181819)
$foreground = rgb(E6D3CB)
$color0 = rgb(3F3F40)
$color1 = rgb(101216)
$color2 = rgb(101216)
$color3 = rgb(594A46)
$color4 = rgb(594A46)
$color5 = rgb(594A46)
$color6 = rgb(8A624F)
$color7 = rgb(D3B8AC)
$color8 = rgb(948178)
$color9 = rgb(16181E)
$color10 = rgb(16181E)
$color11 = rgb(77635D)
$color12 = rgb(77635D)
$color13 = rgb(77635D)
$color14 = rgb(B8826A)
$color15 = rgb(D3B8AC)
