-- @path: user/policy/wallust/wallust-hyprland.lua
-- @author: redskaber
-- @date: 2026-08-20
-- @description: User wallust color overrides — merges with sys defaults
--
-- ARCHITECTURE: This file returns a table of color overrides.
-- Only include colors you want to override; the rest inherit from sys/.
-- The merged result is available as require("user.policy.wallust.wallust-hyprland").
--
-- Colors use #hex format (e.g. "#fafc21").
-- This file is typically auto-generated by wallust on wallpaper change.

local sys_colors = require("sys.policy.wallust.wallust-hyprland")
local M = {}

-- Copy all sys colors as defaults
for k, v in pairs(sys_colors) do
  M[k] = v
end

-- Override specific colors (uncomment to change):
-- M.color12 = "#70717F"  -- active border color
-- M.color10 = "#1F2A35"  -- inactive border color
-- M.background = "#1a1b26"

return M
