#!/usr/bin/env bash
# @path: sys/scripts/lib/common.sh
# @author: redskaber
# @date: 2026-08-20
# @version: 2.1
# @description: Shared shell library — sources SSOT cache + provides helpers
#
# ARCHITECTURE (Task 90): Single Source of Truth (SSOT) pattern.
#   sys/const.lua (Lua) is the SSOT for ALL paths + DI variables.
#   It generates .deps_cache.sh (shell-sourceable) at Hyprland startup.
#   This file sources that cache and adds common helper functions.
#
#   If .deps_cache.sh is missing (e.g. script run before Hyprland starts),
#   fallback defaults are used so scripts still work.
#
# CAPABILITY BOUNDARY (Round 104): These helpers exist because the underlying
#   operations CANNOT be done in Hyprland's Lua API:
#     - hyprctl IPC (Lua has hl.exec_cmd but no JSON query API)
#     - notify-send / rofi / wl-copy (external CLIs, no Lua bindings)
#     - File operations (Lua has io but bash is more ergonomic for shims)
#   Lua-able operations (window kill, lock, etc.) are inlined in keybind.lua
#   via hl.dsp.* — they do NOT need a sh wrapper.
#
# Usage in any .sh script:
#   #!/usr/bin/env bash
#   source "$(dirname "$0")/lib/common.sh"
#   "$NOTIFY" "Hello"                    # tool command (from deps)
#   echo "$SWAYNC_ICONS"                 # external tool path (from const)
#   dt_notify "Title" "Body"             # helper function

# =============================================================================
# Section 1: Source the SSOT cache (auto-generated by sys/const.lua)
# =============================================================================
_DEPS_CACHE="${HYPR_DEPS_CACHE:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr/.deps_cache.sh}"
if [ -f "$_DEPS_CACHE" ]; then
  # shellcheck source=/dev/null
  . "$_DEPS_CACHE"
else
  # ── Fallback defaults (only used if .deps_cache.sh doesn't exist) ────────
  # These match sys/const.lua + lib/deps.lua defaults.
  # Tool commands (from deps.lua specs)
  : "${HYPRCTL:=hyprctl}"
  : "${NOTIFY:=notify-send}"
  : "${ROFI:=rofi}"
  : "${BAR:=waybar}"
  : "${NOTIFICATION:=swaync}"
  : "${JQ:=jq}"
  : "${TERMINAL:=kitty}"
  : "${FILE_MANAGER:=nemo}"
  : "${LAUNCHER:=rofi}"
  : "${BRIGHTNESS_CONTROL:=brightnessctl}"
  : "${VOLUME_CONTROL:=pamixer}"
  : "${MEDIA_CONTROL:=playerctl}"
  : "${CLIPBOARD:=cliphist}"
  : "${WL_PASTE:=wl-paste}"
  : "${WL_COPY:=wl-copy}"
  : "${SCREENSHOT:=grim}"
  : "${SLURP:=slurp}"
  : "${WALLPAPER_DAEMON:=awww-daemon}"
  # Round 110: wallpaper client (companion to wallpaper_daemon)
  : "${WALLPAPER_CLIENT:=awww}"
  # Round 120: widget tools (qs/ags) — for desktop overview
  : "${QUICKSHELL:=qs}"
  : "${AGS:=ags}"
  : "${COLOR_GEN:=wallust}"
  : "${LOCK:=hyprlock}"
  : "${IDLE_DAEMON:=hypridle}"
  : "${NIGHTLIGHT:=hyprsunset}"
  : "${LOGOUT_MENU:=wlogout}"
  : "${EDITOR:=nano}"

  # Round 104: tools not yet in deps.lua but referenced by scripts.
  # These defaults keep scripts working even if .deps_cache.sh is missing.
  : "${FILE_OPENER:=xdg-open}"
  : "${SCREENSHOT_EDITOR:=swappy}"
  : "${CALCULATOR:=qalc}"
  : "${MEDIA_PLAYER:=mpv}"
  : "${VIDEO_WALLPAPER:=mpvpaper}"
  : "${IMAGE_MAGICK:=magick}"
  : "${DIALOG:=yad}"
  : "${CAVA:=cava}"

  # Round 104: HYPR_SEARCH_ENGINE was missing from fallback (RofiSearch.sh
  # depends on it; without it, xdg-open "$query" opens raw query as URL).
  : "${HYPR_SEARCH_ENGINE:=https://www.google.com/search?q=}"

  # Config paths (from bootstrap/const.lua + sys/const.lua)
  : "${HYPR_CONFIG_DIR:=${XDG_CONFIG_HOME:-$HOME/.config}/hypr}"
  : "${HYPR_SCRIPTS_DIR:=$HYPR_CONFIG_DIR/sys/scripts}"
  : "${HYPR_HARDWARE_DIR:=$HYPR_CONFIG_DIR/sys/hardware}"
  : "${HYPR_POLICY_DIR:=$HYPR_CONFIG_DIR/sys/policy}"
  : "${HYPR_USER_DIR:=$HYPR_CONFIG_DIR/user}"
  : "${HYPR_WALLUST_DIR:=$HYPR_CONFIG_DIR/wallust_effects}"
  : "${HYPR_NOTIFY_ICON:=$HYPR_CONFIG_DIR/icon.png}"
  : "${HYPR_LOCK_BG:=$HYPR_WALLUST_DIR/.wallpaper_current}"
  : "${HYPR_WALLPAPER_DIR:=$HOME/Pictures/wallpapers}"
  # Round 109: cache dir (XDG_CACHE_HOME or ~/.cache) for state persistence files
  : "${HYPR_CACHE_DIR:=${XDG_CACHE_HOME:-$HOME/.cache}}"

  # External tool config paths (from sys/const.lua M.external)
  : "${SWAYNC_DIR:=$HOME/.config/swaync}"
  : "${SWAYNC_ICONS:=$SWAYNC_DIR/icons}"
  : "${SWAYNC_IMAGES:=$SWAYNC_DIR/images}"
  : "${ROFI_DIR:=$HOME/.config/rofi}"
  : "${WAYBAR_DIR:=$HOME/.config/waybar}"
  : "${WALLUST_DIR:=$HOME/.config/wallust}"
  : "${KITTY_DIR:=$HOME/.config/kitty}"
  : "${QT_DIR:=$HOME/.config/qt}"

  export HYPRCTL NOTIFY ROFI BAR NOTIFICATION JQ TERMINAL FILE_MANAGER LAUNCHER \
    BRIGHTNESS_CONTROL VOLUME_CONTROL MEDIA_CONTROL CLIPBOARD WL_PASTE WL_COPY \
    SCREENSHOT SLURP WALLPAPER_DAEMON WALLPAPER_CLIENT COLOR_GEN LOCK IDLE_DAEMON NIGHTLIGHT \
    LOGOUT_MENU EDITOR QUICKSHELL AGS \
    FILE_OPENER SCREENSHOT_EDITOR CALCULATOR MEDIA_PLAYER VIDEO_WALLPAPER \
    IMAGE_MAGICK DIALOG CAVA \
    HYPR_CONFIG_DIR HYPR_SCRIPTS_DIR HYPR_HARDWARE_DIR HYPR_POLICY_DIR \
    HYPR_USER_DIR HYPR_WALLUST_DIR HYPR_NOTIFY_ICON HYPR_LOCK_BG \
    HYPR_WALLPAPER_DIR HYPR_SEARCH_ENGINE HYPR_CACHE_DIR \
    SWAYNC_DIR SWAYNC_ICONS SWAYNC_IMAGES ROFI_DIR WAYBAR_DIR \
    WALLUST_DIR KITTY_DIR QT_DIR
fi

# =============================================================================
# Section 2: Helper Functions (common patterns across 60 scripts)
# =============================================================================

# --- Notification helpers ---
dt_notify() {
  local summary="$1" body="${2:-}" urgency="${3:-low}"
  "$NOTIFY" -e -u "$urgency" -i "$HYPR_NOTIFY_ICON" "$summary" "$body"
}

dt_notify_bypass_dnd() {
  local summary="$1" body="${2:-}" urgency="${3:-low}"
  "$NOTIFY" -e -u "$urgency" \
    -h string:x-canonical-private-synchronous:"$(basename "$0" .sh)" \
    -h int:value:0 \
    -h boolean:SWAYNC_BYPASS_DND:true \
    -i "$HYPR_NOTIFY_ICON" "$summary" "$body"
}

# --- Swaync helpers ---
# Round 104: dt_swaync_reload used to do `pkill swaync; swaync &` — this KILLED
# swaync mid-event and caused core dumps (Task 117 regression). swaync is
# designed for live config reload via D-Bus; only waybar can be safely killed.
dt_swaync_toggle() { "${NOTIFICATION}-client" -t -sw 2>/dev/null; }
dt_swaync_reload() { "${NOTIFICATION}-client" --reload-config 2>/dev/null; }

# --- SDDM helpers ---
# SCRIPT-18 fix: extracted the duplicated ~40-line SDDM prompt block that was
# copy-pasted between WallpaperEffects.sh and WallpaperSelect.sh. Behavioural
# canonicalisation: button labels `yes/no`, mode `--normal`, notification via
# dt_notify (critical urgency) when terminal is missing. Runs the wallpaper
# setter in the background so the caller does not block.
# Args: $1 = terminal command, $2 = scripts dir.
dt_sddm_prompt() {
  local terminal="$1"
  local scripts_dir="$2"
  sleep 1
  local sddm_themes_dir=""
  [ -d "/usr/share/sddm/themes" ] && sddm_themes_dir="/usr/share/sddm/themes"
  [ -z "$sddm_themes_dir" ] && [ -d "/run/current-system/sw/share/sddm/themes" ] && sddm_themes_dir="/run/current-system/sw/share/sddm/themes"
  [ -z "$sddm_themes_dir" ] && return 0
  local sddm_simple="$sddm_themes_dir/simple_sddm_2"
  [ -d "$sddm_simple" ] && [ -w "$sddm_simple/Backgrounds" ] || return 0
  pidof yad >/dev/null 2>&1 && killall yad 2>/dev/null || true
  if yad --info --text="Set current wallpaper as SDDM background?\n\nNOTE: This only applies to SIMPLE SDDM v2 Theme" \
    --text-align=left --title="SDDM Background" --timeout=5 --timeout-indicator=right \
    --button="yes:0" --button="no:1"; then
    command -v "$terminal" >/dev/null 2>&1 || {
      dt_notify "Missing $terminal" "Install $terminal to enable setting of wallpaper background" critical
      return 1
    }
    bash "$scripts_dir/sddm_wallpaper.sh" --normal &
  fi
}

# --- Hyprctl helpers ---
# SCRIPT-19 fix: merged the better version from WallustSwww.sh (had an awk
# fallback when jq is unavailable / hyprctl -j fails). The previous helper
# silently returned empty when jq was missing — breaking every caller.
dt_get_focused_monitor() {
  "$HYPRCTL" -j monitors 2>/dev/null | "$JQ" -r '.[] | select(.focused == true) | .name' 2>/dev/null ||
    "$HYPRCTL" monitors 2>/dev/null | awk '/Focused:/ {for(i=1;i<=NF;i++) if($i=="monitor:") print $(i+1)}'
}
dt_get_active_workspace_id() {
  "$HYPRCTL" activeworkspace -j 2>/dev/null | "$JQ" -r '.id'
}
dt_get_active_window_class() {
  "$HYPRCTL" activewindow -j 2>/dev/null | "$JQ" -r '.class'
}
dt_kill_process() { pkill "$1" 2>/dev/null || true; }

# --- Rofi helpers ---
dt_rofi_drun() { "$ROFI" -show drun -modi drun; }
dt_rofi_menu() { "$ROFI" -dmenu -i -p "$1"; }

# --- Waybar helpers ---
dt_waybar_reload() {
  pkill "$BAR" 2>/dev/null
  sleep 0.1
  "$BAR" &
}

# --- Brightness helpers ---
dt_get_brightness() { "$BRIGHTNESS_CONTROL" -m 2>/dev/null | cut -d, -f4 | tr -d '%'; }
dt_set_brightness() { "$BRIGHTNESS_CONTROL" set "$1%"; }

# --- Volume helpers ---
dt_get_volume() { "$VOLUME_CONTROL" --get-volume 2>/dev/null; }

# --- Clipboard helpers ---
dt_clip_list() { "$CLIPBOARD" list; }
dt_clip_copy() { printf '%s' "$1" | "$WL_COPY"; }

# --- Screenshot helpers ---
dt_screenshot_full() {
  local out="${1:-/tmp/screenshot_$(date +%s).png}"
  "$SCREENSHOT" "$out" && echo "$out"
}
dt_screenshot_area() {
  local out="${1:-/tmp/screenshot_$(date +%s).png}"
  local geom
  geom="$("$SLURP" 2>/dev/null)"
  [ -n "$geom" ] && "$SCREENSHOT" -g "$geom" "$out" && echo "$out"
}

# --- Misc ---
dt_log() { echo "[$(basename "$0" .sh)] $*" >&2; }
dt_debug() { [ "${DT_DEBUG:-0}" = "1" ] && dt_log "DEBUG: $*"; }

# --- Hyprland Lua bridge helpers ---
# Round 107: wrapper for the `hyprctl eval "hl.dispatch(...)"` pattern used by
# sh scripts to call the Lua dispatcher API (the only way to invoke hl.dsp.*
# from sh). Centralizes error suppression + makes future logging/debugging easy.
#
# Usage: dt_hl_dispatch 'hl.dsp.window.move({workspace="1",follow=false})'
#   $1 = the full hl.dsp.X({...}) expression (without the wrapping hl.dispatch)
dt_hl_dispatch() {
  "$HYPRCTL" eval "hl.dispatch($1)" >/dev/null 2>&1
}

# Query Hyprland state via hyprctl -j (JSON output) + jq filter.
# Usage: dt_hyprctl_json "activewindow" ".class // empty"
#   $1 = hyprctl subcommand (e.g. "activewindow", "monitors", "clients")
#   $2 = jq filter (optional, defaults to "." for raw JSON)
dt_hyprctl_json() {
  local subcmd="$1"
  local filter="${2:-.}"
  "$HYPRCTL" -j "$subcmd" 2>/dev/null | "$JQ" -r "$filter" 2>/dev/null
}
