#!/usr/bin/env bash
# @path: sys/scripts/lib/common.sh
# @author: redskaber
# @date: 2026-08-20
# @version: 2.0
# @description: Shared shell library — sources SSOT cache + provides helpers
#
# ARCHITECTURE (Task 90): Single Source of Truth (SSOT) pattern.
#   sys/const.lua (Lua) is the SSOT for ALL paths + DI variables.
#   It generates .deps_cache.sh (shell-sourceable) at Hyprland startup.
#   This file sources that cache and adds common helper functions.
#
#   If .deps_cache.sh is missing (e.g. script run before Hyprland starts),
#   fallback defaults are used so scripts still work.
#
# Usage in any .sh script:
#   #!/usr/bin/env bash
#   source "$(dirname "$0")/lib/common.sh"
#   "$NOTIFY" "Hello"                    # tool command (from deps)
#   echo "$SWAYNC_ICONS"                 # external tool path (from const)
#   dt_notify "Title" "Body"             # helper function

# =============================================================================
# Section 1: Source the SSOT cache (auto-generated by sys/const.lua)
# =============================================================================
_DEPS_CACHE="${HYPR_DEPS_CACHE:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr/.deps_cache.sh}"
if [ -f "$_DEPS_CACHE" ]; then
  # shellcheck source=/dev/null
  . "$_DEPS_CACHE"
else
  # ── Fallback defaults (only used if .deps_cache.sh doesn't exist) ────────
  # These match sys/const.lua + lib/deps.lua defaults.
  # Tool commands (from deps.lua specs)
  : "${HYPRCTL:=hyprctl}"
  : "${NOTIFY:=notify-send}"
  : "${ROFI:=rofi}"
  : "${BAR:=waybar}"
  : "${NOTIFICATION:=swaync}"
  : "${JQ:=jq}"
  : "${TERMINAL:=kitty}"
  : "${FILE_MANAGER:=nemo}"
  : "${LAUNCHER:=rofi}"
  : "${BRIGHTNESS_CONTROL:=brightnessctl}"
  : "${VOLUME_CONTROL:=pamixer}"
  : "${MEDIA_CONTROL:=playerctl}"
  : "${CLIPBOARD:=cliphist}"
  : "${WL_PASTE:=wl-paste}"
  : "${WL_COPY:=wl-copy}"
  : "${SCREENSHOT:=grim}"
  : "${SLURP:=slurp}"
  : "${WALLPAPER_DAEMON:=awww-daemon}"
  : "${COLOR_GEN:=wallust}"
  : "${LOCK:=hyprlock}"
  : "${IDLE_DAEMON:=hypridle}"
  : "${NIGHTLIGHT:=hyprsunset}"
  : "${LOGOUT_MENU:=wlogout}"
  : "${EDITOR:=nano}"

  # Config paths (from bootstrap/const.lua + sys/const.lua)
  : "${HYPR_CONFIG_DIR:=${XDG_CONFIG_HOME:-$HOME/.config}/hypr}"
  : "${HYPR_SCRIPTS_DIR:=$HYPR_CONFIG_DIR/sys/scripts}"
  : "${HYPR_HARDWARE_DIR:=$HYPR_CONFIG_DIR/sys/hardware}"
  : "${HYPR_POLICY_DIR:=$HYPR_CONFIG_DIR/sys/policy}"
  : "${HYPR_USER_DIR:=$HYPR_CONFIG_DIR/user}"
  : "${HYPR_WALLUST_DIR:=$HYPR_CONFIG_DIR/wallust_effects}"
  : "${HYPR_NOTIFY_ICON:=$HYPR_CONFIG_DIR/icon.png}"
  : "${HYPR_LOCK_BG:=$HYPR_WALLUST_DIR/.wallpaper_current}"
  : "${HYPR_WALLPAPER_DIR:=$HOME/Pictures/wallpapers}"

  # External tool config paths (from sys/const.lua M.external)
  : "${SWAYNC_DIR:=$HOME/.config/swaync}"
  : "${SWAYNC_ICONS:=$SWAYNC_DIR/icons}"
  : "${SWAYNC_IMAGES:=$SWAYNC_DIR/images}"
  : "${ROFI_DIR:=$HOME/.config/rofi}"
  : "${WAYBAR_DIR:=$HOME/.config/waybar}"
  : "${WALLUST_DIR:=$HOME/.config/wallust}"
  : "${KITTY_DIR:=$HOME/.config/kitty}"
  : "${QT_DIR:=$HOME/.config/qt}"

  export HYPRCTL NOTIFY ROFI BAR NOTIFICATION JQ TERMINAL FILE_MANAGER LAUNCHER \
         BRIGHTNESS_CONTROL VOLUME_CONTROL MEDIA_CONTROL CLIPBOARD WL_PASTE WL_COPY \
         SCREENSHOT SLURP WALLPAPER_DAEMON COLOR_GEN LOCK IDLE_DAEMON NIGHTLIGHT \
         LOGOUT_MENU EDITOR \
         HYPR_CONFIG_DIR HYPR_SCRIPTS_DIR HYPR_HARDWARE_DIR HYPR_POLICY_DIR \
         HYPR_USER_DIR HYPR_WALLUST_DIR HYPR_NOTIFY_ICON HYPR_LOCK_BG \
         HYPR_WALLPAPER_DIR \
         SWAYNC_DIR SWAYNC_ICONS SWAYNC_IMAGES ROFI_DIR WAYBAR_DIR \
         WALLUST_DIR KITTY_DIR QT_DIR
fi

# =============================================================================
# Section 2: Helper Functions (common patterns across 60 scripts)
# =============================================================================

# --- Notification helpers ---
dt_notify() {
  local summary="$1" body="${2:-}" urgency="${3:-low}"
  "$NOTIFY" -e -u "$urgency" -i "$HYPR_NOTIFY_ICON" "$summary" "$body"
}

dt_notify_bypass_dnd() {
  local summary="$1" body="${2:-}" urgency="${3:-low}"
  "$NOTIFY" -e -u "$urgency" \
    -h string:x-canonical-private-synchronous:"$(basename "$0" .sh)" \
    -h int:value:0 \
    -h boolean:SWAYNC_BYPASS_DND:true \
    -i "$HYPR_NOTIFY_ICON" "$summary" "$body"
}

# --- Swaync helpers ---
dt_swaync_toggle() { "${NOTIFICATION}-client" -t -sw 2>/dev/null; }
dt_swaync_reload() { pkill "${NOTIFICATION}" 2>/dev/null; sleep 0.1; "$NOTIFICATION" & }

# --- Hyprctl helpers ---
dt_get_focused_monitor() {
  "$HYPRCTL" -j monitors 2>/dev/null | "$JQ" -r '.[] | select(.focused == true) | .name'
}
dt_get_active_workspace_id() {
  "$HYPRCTL" activeworkspace -j 2>/dev/null | "$JQ" -r '.id'
}
dt_get_active_window_class() {
  "$HYPRCTL" activewindow -j 2>/dev/null | "$JQ" -r '.class'
}
dt_kill_process() { pkill "$1" 2>/dev/null || true; }

# --- Rofi helpers ---
dt_rofi_drun() { "$ROFI" -show drun -modi drun; }
dt_rofi_menu() { "$ROFI" -dmenu -i -p "$1"; }

# --- Waybar helpers ---
dt_waybar_reload() { pkill "$BAR" 2>/dev/null; sleep 0.1; "$BAR" & }

# --- Brightness helpers ---
dt_get_brightness() { "$BRIGHTNESS_CONTROL" -m 2>/dev/null | cut -d, -f4 | tr -d '%'; }
dt_set_brightness() { "$BRIGHTNESS_CONTROL" set "$1%"; }

# --- Volume helpers ---
dt_get_volume() { "$VOLUME_CONTROL" --get-volume 2>/dev/null; }

# --- Clipboard helpers ---
dt_clip_list() { "$CLIPBOARD" list; }
dt_clip_copy() { printf '%s' "$1" | "$WL_COPY"; }

# --- Screenshot helpers ---
dt_screenshot_full() {
  local out="${1:-/tmp/screenshot_$(date +%s).png}"
  "$SCREENSHOT" "$out" && echo "$out"
}
dt_screenshot_area() {
  local out="${1:-/tmp/screenshot_$(date +%s).png}"
  local geom; geom="$("$SLURP" 2>/dev/null)"
  [ -n "$geom" ] && "$SCREENSHOT" -g "$geom" "$out" && echo "$out"
}

# --- Misc ---
dt_log() { echo "[$(basename "$0" .sh)] $*" >&2; }
dt_debug() { [ "${DT_DEBUG:-0}" = "1" ] && dt_log "DEBUG: $*"; }
