#!/bin/sh
# @path: sys/scripts/lib/common.sh
# @author: redskaber
# @date: 2026-08-20
# @version: 1.0
# @description: Shared shell library — DI for .sh scripts (shell equivalent of lib/script_utils.lua)
#
# This is the 通解 (general solution) for the 451 hard-coded tool names across 60 .sh scripts.
# Instead of migrating each script individually, this library provides:
#   1. Auto-sources the deps cache (generated by lib/deps.lua at Hyprland startup)
#   2. Helper functions for common patterns (notify, rofi, swaync, hyprctl wrappers)
#   3. Fallback defaults if the cache is missing (graceful degradation)
#
# Usage in any .sh script:
#   #!/usr/bin/env bash
#   source "$(dirname "$0")/lib/common.sh"
#   dt_notify "Title" "Body"
#   dt_swaync_toggle
#
# Design principles applied:
#   - Dependency Injection: tool names resolved via deps cache, not hard-coded
#   - Single Source of Truth: deps.lua is the only declaration; common.sh is the only shell entry
#   - Graceful Degradation: fallback defaults if cache missing (scripts still work)
#   - DRY: 60 scripts share one library, not 60 copies of the same logic

# =============================================================================
# Section 1: Dependency Injection — source the deps cache
# =============================================================================
# The cache is generated by lib/deps.lua M.export_to_shell() at Hyprland startup.
# It exports UPPER_SNAKE_CASE variables: HYPRCTL, NOTIFY_SEND, ROFI, SWAYNC, etc.
# If missing (e.g. Hyprland not yet started), fall back to common defaults.

_DEPS_CACHE="${HYPR_DEPS_CACHE:-$HOME/.config/hypr/.deps_cache.sh}"
if [ -f "$_DEPS_CACHE" ]; then
  # shellcheck source=/dev/null
  . "$_DEPS_CACHE"
else
  # Fallback defaults — keep scripts working even without Hyprland-generated cache.
  # These MUST match lib/deps.lua M.specs defaults.
  : "${HYPRCTL:=hyprctl}"
  : "${NOTIFY:=notify-send}"
  : "${ROFI:=rofi}"
  : "${BAR:=waybar}"
  : "${NOTIFICATION:=swaync}"
  : "${JQ:=jq}"
  : "${TERMINAL:=kitty}"
  : "${FILE_MANAGER:=nemo}"
  : "${LAUNCHER:=rofi}"
  : "${BRIGHTNESS_CONTROL:=brightnessctl}"
  : "${VOLUME_CONTROL:=pamixer}"
  : "${MEDIA_CONTROL:=playerctl}"
  : "${CLIPBOARD:=cliphist}"
  : "${WL_PASTE:=wl-paste}"
  : "${WL_COPY:=wl-copy}"
  : "${SCREENSHOT:=grim}"
  : "${SLURP:=slurp}"
  : "${WALLPAPER_DAEMON:=awww-daemon}"
  : "${COLOR_GEN:=wallust}"
  : "${LOCK:=hyprlock}"
  : "${IDLE_DAEMON:=hypridle}"
  : "${NIGHTLIGHT:=hyprsunset}"
  : "${LOGOUT_MENU:=wlogout}"
  : "${EDITOR:=nano}"
fi

# Export so child processes (subshells) inherit
export HYPRCTL NOTIFY ROFI BAR NOTIFICATION JQ TERMINAL FILE_MANAGER LAUNCHER \
       BRIGHTNESS_CONTROL VOLUME_CONTROL MEDIA_CONTROL CLIPBOARD WL_PASTE WL_COPY \
       SCREENSHOT SLURP WALLPAPER_DAEMON COLOR_GEN LOCK IDLE_DAEMON NIGHTLIGHT \
       LOGOUT_MENU EDITOR

# =============================================================================
# Section 2: Path Constants (mirror _G.HYPR_CONST in shell)
# =============================================================================
HYPR_CONFIG_DIR="${HYPR_CONFIG_DIR:-$HOME/.config/hypr}"
HYPR_SCRIPTS_DIR="$HYPR_CONFIG_DIR/sys/scripts"
HYPR_HARDWARE_DIR="$HYPR_CONFIG_DIR/sys/hardware"
HYPR_POLICY_DIR="$HYPR_CONFIG_DIR/sys/policy"
HYPR_USER_DIR="$HYPR_CONFIG_DIR/user"
HYPR_NOTIFY_ICON="$HYPR_CONFIG_DIR/icon.png"
HYPR_WALLPAPER_DIR="${HYPR_WALLPAPER_DIR:-$HYPR_CONFIG_DIR/Pictures/wallpapers}"

export HYPR_CONFIG_DIR HYPR_SCRIPTS_DIR HYPR_HARDWARE_DIR HYPR_POLICY_DIR \
       HYPR_USER_DIR HYPR_NOTIFY_ICON HYPR_WALLPAPER_DIR

# =============================================================================
# Section 3: Helper Functions (common patterns across 60 scripts)
# =============================================================================

# --- Notification helpers (27 scripts use notify-send) ---

# dt_notify <summary> <body> [urgency]
#   Standard notification with project icon. urgency: low (default) / normal / critical.
dt_notify() {
  local summary="$1" body="${2:-}" urgency="${3:-low}"
  "$NOTIFY" -e -u "$urgency" -i "$HYPR_NOTIFY_ICON" "$summary" "$body"
}

# dt_notify_bypass_dnd <summary> <body> [urgency]
#   Notification that bypasses swaync Do Not Disturb.
dt_notify_bypass_dnd() {
  local summary="$1" body="${2:-}" urgency="${3:-low}"
  "$NOTIFY" -e -u "$urgency" \
    -h string:x-canonical-private-synchronous:"$(basename "$0" .sh)" \
    -h int:value:0 \
    -h boolean:SWAYNC_BYPASS_DND:true \
    -i "$HYPR_NOTIFY_ICON" "$summary" "$body"
}

# --- Swaync helpers (28 scripts use swaync) ---

# dt_swaync_toggle — toggle the notification center
dt_swaync_toggle() {
  "${NOTIFICATION}-client" -t -sw 2>/dev/null
}

# dt_swaync_reload — restart swaync
dt_swaync_reload() {
  pkill "${NOTIFICATION}" 2>/dev/null
  sleep 0.1
  "$NOTIFICATION" &
}

# --- Hyprctl helpers (20 scripts use hyprctl) ---

# dt_get_focused_monitor — echo the focused monitor name (e.g. "DP-1")
dt_get_focused_monitor() {
  "$HYPRCTL" -j monitors 2>/dev/null | "$JQ" -r '.[] | select(.focused == true) | .name'
}

# dt_get_active_workspace_id — echo the active workspace ID
dt_get_active_workspace_id() {
  "$HYPRCTL" activeworkspace -j 2>/dev/null | "$JQ" -r '.id'
}

# dt_get_active_window_class — echo the active window's class
dt_get_active_window_class() {
  "$HYPRCTL" activewindow -j 2>/dev/null | "$JQ" -r '.class'
}

# dt_get_window_by_class <class_regex> — echo first matching window address
dt_get_window_by_class() {
  local class_regex="$1"
  "$HYPRCTL" clients -j 2>/dev/null | "$JQ" -r --arg R "$class_regex" \
    '.[] | select(.class | test($R)) | .address' | head -1
}

# dt_kill_process <name> — kill a process safely (no error if not running)
dt_kill_process() {
  local name="$1"
  pkill "$name" 2>/dev/null || true
}

# --- Rofi helpers (25 scripts use rofi) ---

# dt_rofi_drun — app launcher (drun mode)
dt_rofi_drun() {
  "$ROFI" -show drun -modi drun
}

# dt_rofi_menu <prompt> <entries_file> — generic menu
#   Reads entries from stdin, echoes selected.
dt_rofi_menu() {
  local prompt="$1"
  "$ROFI" -dmenu -i -p "$prompt"
}

# --- Waybar helpers (6 scripts) ---

# dt_waybar_reload — restart waybar
dt_waybar_reload() {
  pkill "$BAR" 2>/dev/null
  sleep 0.1
  "$BAR" &
}

# --- Brightness helpers (2 scripts) ---

# dt_get_brightness — echo current brightness as integer (0-100)
dt_get_brightness() {
  "$BRIGHTNESS_CONTROL" -m 2>/dev/null | cut -d, -f4 | tr -d '%'
}

# dt_set_brightness <percent>
dt_set_brightness() {
  "$BRIGHTNESS_CONTROL" set "$1%"
}

# --- Volume helpers ---

# dt_get_volume — echo current volume as integer
dt_get_volume() {
  "$VOLUME_CONTROL" get-sink-volume @DEFAULT_SINK@ 2>/dev/null | "$JQ" -r '.volume | .[0].volume_percent'
}

# --- Clipboard helpers (2 scripts) ---

# dt_clip_list — list clipboard history
dt_clip_list() {
  "$CLIPBOARD" list
}

# dt_clip_copy <text>
dt_clip_copy() {
  printf '%s' "$1" | "$WL_PASTE" --type text
}

# --- Screenshot helpers (2 scripts) ---

# dt_screenshot_full — capture full screen to file
dt_screenshot_full() {
  local out="${1:-/tmp/screenshot_$(date +%s).png}"
  "$SCREENSHOT" "$out" && echo "$out"
}

# dt_screenshot_area — capture selected region to file
dt_screenshot_area() {
  local out="${1:-/tmp/screenshot_$(date +%s).png}"
  local geom
  geom="$("$SLURP" 2>/dev/null)"
  [ -n "$geom" ] && "$SCREENSHOT" -g "$geom" "$out" && echo "$out"
}

# --- Misc ---

# dt_log <message> — log to stderr (visible in journalctl)
dt_log() {
  echo "[$(basename "$0" .sh)] $*" >&2
}

# dt_debug <message> — log only if DT_DEBUG=1
dt_debug() {
  [ "${DT_DEBUG:-0}" = "1" ] && dt_log "DEBUG: $*"
}

# =============================================================================
# Section 4: Self-test (source with DT_SELF_TEST=1 to run)
# =============================================================================
if [ "${DT_SELF_TEST:-0}" = "1" ]; then
  echo "=== common.sh self-test ==="
  echo "HYPRCTL=$HYPRCTL"
  echo "NOTIFY=$NOTIFY"
  echo "ROFI=$ROFI"
  echo "JQ=$JQ"
  echo "BRIGHTNESS_CONTROL=$BRIGHTNESS_CONTROL"
  echo "HYPR_SCRIPTS_DIR=$HYPR_SCRIPTS_DIR"
  echo "=== helper functions defined ==="
  for fn in dt_notify dt_swaync_toggle dt_get_focused_monitor dt_rofi_menu; do
    type "$fn" >/dev/null 2>&1 && echo "  ✓ $fn" || echo "  ✗ $fn MISSING"
  done
fi
