-- @path: user/tags.lua
-- @author: redskaber
-- @date: 2026-08-20
-- @description: User tag additions
--
-- user/tags.lua — User overrides for sys/tags.lua
-- Edit this file to customize tags settings (incremental override pattern).
-- Only specify differences from sys/tags.lua; sys defaults inherit automatically.
